data:
  target: dataset.data_module.BIRDataModule
  params:
    # Path to training set configuration file.
    train_config: path/to/your/file
    # Path to validation set configuration file.
    val_config: path/to/your/file

model:
  # You can set learning rate in the following configuration file.
  config: configs/model/swinir.yaml
  # Path to the checkpoints or weights you want to resume.
  resume: ~

lightning:
  seed: 231
  
  trainer:
    # accelerator: ddp
    accelerator: auto

    precision: 32
    # Indices of GPUs used for training.
    # gpus: [0,1,2,3]
    # gpu: [0]

    # Path to save logs and checkpoints.
    default_root_dir: ./experiment
    # Max number of training steps (batches).
    max_steps: 300001
    # Validation frequency in terms of training steps.
    val_check_interval: 152
    # Log frequency of tensorboard logger.
    log_every_n_steps: 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  callbacks:
    - target: model.callbacks.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 10000
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.
        every_n_train_steps: 20000
        save_top_k: -1
        filename: "{step}"
